<a href="https://colab.research.google.com/github/Jonathan-Gil-Muller/Analise-Exploratoria-Dados_-BCD-/blob/main/AED_%5BTurmaB_BCD%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SEU-USUARIO/NOME-DO-REPOSITORIO/blob/main/aula01.ipynb)

**Análise Exploratória de Dados**

*Prof. Jonathan Gil Müller*

2026/2

# **Mensagens_chave das aulas**

**MENSAGEM CHAVE DA AULA 1**:


*   ORGANIZAÇÃO DE DADOS: Antes de iniciar a análise dos dados, é importante deixarmos os dados (tabelas) organizados (Tidy Data). Um conjunto de dados está organizado quando atende o padrão de: (i) cada tipo de informação esta em uma coluna diferente; (ii) cada observação/cenário está em uma linha diferentes; e (iii) os dados/informações estão nas células da matriz/tabela.


*   MANIPULAÇÃO DE TABELAS: existem vários recursos na linguagem Python (biblioteca Pandas) para manipulação de tabelas. Algumas funcionalidades são: eliminar duplicatas, padronizar os rótulos das colunas e as strins dos dados (maiúsculo/minúsculo), remover espaços, criar novas colunas, preencher células vazias, ordenação (alfabética, crescente).

**MENSAGEM CHAVE DA AULA 2**:


*   REESTRUTURAÇÃO E PIVOTAMENTO DE DADOS: pivotamento consiste em compactar uma tabela no padrão de máquina (longa) para o padrão humano (largo). Podemos fazer isso utilizando a função do Pandas pivot(). Já a reestruturação de uma tabela consiste em transformar uma tabela do formato humano (largo) para o formato de máquina (longo), ou seja, formato organizado. Podemos fazer a reestruturação utilizando a função do Pandas: melt().


*   CONCATENAÇÃO E FUSÃO DE CONJUNTO DE DADOS:consiste no conceito de unir tabelas de diferentes formas. A concatenação consiste no empilhamento de tabelas, desde que tenham as mesmas informações (colunas) ou cenários (linhas). O empilhamento pode acontecer na vertical (aumenta o n. de linhas, axis=0) ou na horinzontal (aumenta o n. de colunas, axis=1). A concatenação é implementada por meio da função pd.concat(). Já a fusão consiste em combinar duas tabelas a partir de uma coluna comum (chave). Existe mais de uma forma de concatenação, por exemplo: left (tudo que tem na primeira), right (tudo o que tem na segunda), inner (tem nas duas simultaneamente), outer (soma das duas tabelas), entre outras. A fusão de tabelas e realizada por meio da função pd.merge(), da biblioteca Pandas.

*   INDEXAÇÃO E FERRAMENTAS DE BUSCA: a indezação serve como coordenada para filtragem de dados com base no endereço de linhas e colunas. A ordem de leitura é sempre primeiro linha e depois coluna. Os endereços/coordenadas das linhas e colunas pode ser o numérico padrão (índice padrão) ou alguma coluna especificada (indice semantico). Um ponto de atenção é que o índice padrão não é fixo da linha, caso a tabela seja reordenada. Nesses casos de reordenação dos dados, o índice semântico será mais assertivo. As principais ferramentas de busca baseadas en índice são: iloc() - baseado em número, ou seja, índice padrão, e a função loc() - baseada no índice semântico. Além disso, a soma de dataframes também ocorre em função dos índices e não por célula correspondente.

**MENSAGEM CHAVE DA AULA 3**:


*   QUALIDADE DE DADOS: a qualidade dos dados é importante para garantir/assegurar bons resultados na análise ou modelagem. A qualidade de um conjunto de dados é vericada com base na existência de valores ausentes, inconsistentes, redundates, ruidosos, tendenciosos, como também em função da forma como os dados foram obtidos (fonte, equipamento e dispositivos utilizados, período de tempo, ...).

* TRATAMENTO DE VALORES AUSENTES: é importante entender os mecanismos que explicam o motivo da ausência daquelas informações (dados), ou seja, se aquela ausência é aleatória (não possui nenhum padrão e não é previsível), se ela depende da informação de outros atributos, ou se ela é previsível (não aleatória) e tem algum padrão que justifique a sua ausência. As formas de lidar com os valores ausentes são: desconsiderar a ausência (caso futuros modelos suportem essa condição); descartar os objetos (linhas), descartar os atributos (colunas); substituir por um valor fictício representativo; ou substituir por uma estimativa. Além disso, é muito importante, criar uma nova coluna preditiva com valores binários indicando a ausência (1) ou não ausência (0) de valor no atributo original.

**MENSAGEM CHAVE DA AULA 4**:


*   TRANSFORMAÇÃO DE DADOS: Consiste em um conjunto de regras para alterar as informações de atributos. A finalidade da transformação de dados consiste em alterar os valores para garantir a anonimização da informação, bem como, converter e transformar valores e escalas dentro dos padrões necessários para a análise. Tudo isso, sem descaracterizar a essencial informação (variabilidade e distribuição).

* ANONIMIZAÇÃO: consiste em mascarar os valores para manter a privacidade e segurança de dados pessoais ou institucionais. A anonimização é realizada em função do tipo do dado do atributo (categórico, ordinal e numérico). A anonimização dos atributos categóricos é feita a partir da substituição das classes por novos valores fictícios (ex: letras). Já os atributos ordinais, pode ser substituido por uma sequência numérica que respeite a ordem e a sequência das classes do atributo original (ex: 1, 2, 3; ou 10, 20, 30). Por fim, os atributos numpericos podem ser anonimizados através de funções matemáticas, normalmente, envolvendo somas, subtrações e multiplicação. As respectivas funções inversas podem ser utilizadas para reversão dos valores (recuperar valores originais). É importante que o analista crie uma tabela com as regras de anonimização utilizadas para possibilitar a conversão de volta para os valores originais, caso necessário.

**MENSAGEM CHAVE DA AULA 5**:


*   CONVERSÃO DE DADOS: transformar/mudar o valor é a categoria do dados, ou seja, de quantitativo para qualitativo ou vice-versa. a covnersão de valores é realizada para ajustar/adaptar os dados aos requisitos de funcionamento dos modelos e métodos de análise utilizados em etapas seguintes do projeto. A implementação da conversão de dados depende do tipo da conversão que precisa ser realizada. (a) Para converter um dado ordinal em numérico, basta organizar os atributos em ordem e substituir pela sua respectiva posição. (b) Já para converter um dado nominal em numérico, precisamos realizar uma conversão do tipo binária (1-de-n, one-hot, hot-encoding), onde, cada categoria do atributo nominal vira uma nova coluna binária. Essa estratégia evita introduzis nos dados convertidos informações de ordem e distância que não existem nos dados originais. Quando um atributo nominal possui muitas categorias distintas, uma estratégia é utilizar combinações de pseudo-atributos numéricos. (C) Por fim, para converter uma atributo numérico para qualitativo, precisamos discretizar o intervalo original em subintervalos (utilizando critérios técnicos ou estatísticos), nomear cada um deles, e classificar cada dado numérico de acordo com seu respectivo intervalo de pertencimento.

# **SLIDE 01: organização e estruturação de dados**

## Atividade 1

In [ ]:
import pandas as pd

In [ ]:
# 1. Carragar DataFrame
dados = {
    'ID Vendedor': [101, 102, 101, 103, 104],
    'Região': ['Sul', 'NORTE', 'Sul', 'sul', 'Leste'],
    'FATURAMENTO': [5000, 3000, 5000, np.nan, 4500],
    'Email': [
        'ana@furb.br',
        'bruno@furb.br',
        'ana@furb.br',
        'carla@furb.br',
        'joao@furb.br',
    ]
}

df = pd.DataFrame(dados)
print(df)

# Carregar diretamento do Excel
#df = pd.read_excel("file_name")

   ID Vendedor Região  FATURAMENTO          Email
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
2          101    Sul       5000.0    ana@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 2. Renomeação das colunas

df1 = df.rename(columns={
    'ID Vendedor': 'ID_VENDEDOR',
    'Região': 'REGIAO',
    'Email': 'EMAIL'
})

print(df1)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
2          101    Sul       5000.0    ana@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 3. Eliminação de duplicatas

df2 = df1.drop_duplicates(subset=['EMAIL'])
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 4. Tratamento de Dados Ausentes

df2['FATURAMENTO'] = df2['FATURAMENTO'].fillna(0)

print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
3          103    sul          0.0  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

/tmp/ipykernel_598/3316359745.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['FATURAMENTO'] = df2['FATURAMENTO'].fillna(0)

In [ ]:
# 5. Criação de uma coluna calculada

df2['FATURAMENTO-ANUAL'] = df2['FATURAMENTO']*12
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

/tmp/ipykernel_598/1095340127.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['FATURAMENTO-ANUAL'] = df2['FATURAMENTO']*12

In [ ]:
# 5. Criação de uma nova coluna com lista de valores

df2['PERC-COMISSAO'] = [10, 20, 15, 10]
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

   PERC-COMISSAO
0             10
1             20
3             15
4             10

/tmp/ipykernel_598/2344827271.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['PERC-COMISSAO'] = [10, 20, 15, 10]

In [ ]:
# 5. Criação de uma nova coluna operando com mais de uma coluna

df2['LUCRO'] = df2['FATURAMENTO-ANUAL'] - df2['PERC-COMISSAO']/100 * df2['FATURAMENTO-ANUAL']
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

   PERC-COMISSAO    LUCRO
0             10  54000.0
1             20  28800.0
3             15      0.0
4             10  48600.0

/tmp/ipykernel_598/2443526130.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['LUCRO'] = df2['FATURAMENTO-ANUAL'] - df2['PERC-COMISSAO']/100 * df2['FATURAMENTO-ANUAL']

In [ ]:
# 6. Padronização e ordenação

df2['REGIAO'] = df2['REGIAO'].str.lower()
df2 = df2.sort_values(by='FATURAMENTO', ascending=False)

print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    sul       5000.0    ana@furb.br            60000.0
4          104  leste       4500.0   joao@furb.br            54000.0
1          102  norte       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0

   PERC-COMISSAO    LUCRO
0             10  54000.0
4             10  48600.0
1             20  28800.0
3             15      0.0

In [ ]:
# 7. Exportação Final

df2.to_excel('dados_processados.xlsx', index=False)
df2.to_csv('dados_processados.csv', index=False)

## Atividade 2

In [ ]:
import pandas as pd

In [ ]:
# 1. Carregando os dados no Formato Largo (Wide)
df_notas = pd.DataFrame({
    'Estudante': ['Alice', 'Bruno', 'Carla'],
    'Matematica': [8.5, 7.0, 9.5],
    'Ciencias': [9.0, 6.5, 8.0],
    'Historia': [7.0, 8.0, 8.5]
})

print(df_notas)

  Estudante  Matematica  Ciencias  Historia
0     Alice         8.5       9.0       7.0
1     Bruno         7.0       6.5       8.0
2     Carla         9.5       8.0       8.5

In [ ]:
# 2. Transformando em Formato Longo com pd.melt()

df_longo = pd.melt(df_notas,
                   id_vars=['Estudante'],
                   value_vars=['Matematica', 'Ciencias', 'Historia'],
                   var_name='Disciplina',
                   value_name='Nota')

print(df_longo)

In [ ]:
# 3. Reorganizando com pd.pivot()

df_boletim = df_longo.pivot(index='Estudante',
                            columns='Disciplina',
                            values='Nota')

print("\nTabela Pivoteada (Retorno ao Formato Largo):")
print(df_boletim)

## Atividade 3

In [ ]:
import pandas as pd

In [ ]:
# 1. Criando as tabelas

df_alunos = pd.DataFrame({
    'id_aluno': [1, 2, 3, 4, 5],
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana', 'Eduardo']
})

df_novos_alunos = pd.DataFrame({
    'id_aluno': [6, 7, 8, 9, 10],
    'Nome': ['Fernanda', 'Gabriel', 'Helena', 'Igor', 'Julia']
})

df_notas = pd.DataFrame({
    'id_aluno': [1, 2, 4, 6, 8, 11],
    'Nota_Final': [8.5, 7.0, 9.2, 6.5, 8.0, 10.0]
})

print('df_alunos')
print(df_alunos,'\n')
print('df_novos_alunos')
print(df_novos_alunos,'\n')
print('df_notas')
print(df_notas)

df_alunos
   id_aluno     Nome
0         1      Ana
1         2    Bruno
2         3   Carlos
3         4    Diana
4         5  Eduardo

df_novos_alunos
   id_aluno      Nome
0         6  Fernanda
1         7   Gabriel
2         8    Helena
3         9      Igor
4        10     Julia

df_notas
   id_aluno  Nota_Final
0         1         8.5
1         2         7.0
2         4         9.2
3         6         6.5
4         8         8.0
5        11        10.0

In [ ]:
# 2. Empilhar as listas de alunos

df_alunos_completo = pd.concat([df_alunos, df_novos_alunos], ignore_index=True)

print('df_alunos_completo')
print(df_alunos_completo)

df_alunos_completo
   id_aluno      Nome
0         1       Ana
1         2     Bruno
2         3    Carlos
3         4     Diana
4         5   Eduardo
5         6  Fernanda
6         7   Gabriel
7         8    Helena
8         9      Igor
9        10     Julia

In [ ]:
# 3. Cruzamento da lista de alunos com o registro das notas

df_relatorio_final = pd.merge(df_alunos_completo,
                              df_notas,
                              on='id_aluno',
                              how='outer')

print("df_relatorio_final")
print(df_relatorio_final)

df_relatorio_final
    id_aluno      Nome  Nota_Final
0          1       Ana         8.5
1          2     Bruno         7.0
2          3    Carlos         NaN
3          4     Diana         9.2
4          5   Eduardo         NaN
5          6  Fernanda         6.5
6          7   Gabriel         NaN
7          8    Helena         8.0
8          9      Igor         NaN
9         10     Julia         NaN
10        11       NaN        10.0

## Atividade 4

In [ ]:
import pandas as pd

In [ ]:
# 1. Criando as tabelas: usar o DataFrame df_relatorio_final da atividade 3

# 2. Filtrar alunos que estão sem nota (NaN)

sem_nota = df_relatorio_final.loc[df_relatorio_final['Nota_Final'].isna()]

print(sem_nota)

   id_aluno     Nome  Nota_Final
2         3   Carlos         NaN
4         5  Eduardo         NaN
6         7  Gabriel         NaN
8         9     Igor         NaN
9        10    Julia         NaN

In [ ]:
# 3. Filtrar os 3 primeiros registros (posições 0, 1 e 2)
tres_primeiros = df_relatorio_final.iloc[0:3]

print(tres_primeiros)

   id_aluno    Nome  Nota_Final
0         1     Ana         8.5
1         2   Bruno         7.0
2         3  Carlos         NaN

In [ ]:
# 4. Filtros por linha e coluna

filtro = df_relatorio_final.iloc[0:3, 2]

print(filtro)

0    8.5
1    7.0
2    NaN
Name: Nota_Final, dtype: float64

# **SLIDE 02: tratamento e qualidade de dados**

## Atividade 1

In [ ]:
import pandas as pd
import numpy as np

# Dataframe com os dados
df = pd.DataFrame({
    'Nome': ['Alberto', 'Bárbara', 'Cláudia', 'Pedro', 'Rosa', 'Rui'],
    'Batimento': [65, 88, 74, np.nan, np.nan, 60],
    'Pressão': [132, 90, np.nan, 115, 86, 138],
    'Temperatura': [38, np.nan, 38, 36, 37, 39],
    'Sintoma': ['Nenhum', np.nan, np.nan, 'Dor no peito', np.nan, np.nan],
    'Diagnóstico': ['Doente', 'Saudável', 'Saudável', 'Doente', 'Saudável', 'Doente']
})

# Exibindo a tabela
print(df)

      Nome  Batimento  Pressão  Temperatura       Sintoma Diagnóstico
0  Alberto       65.0    132.0         38.0        Nenhum      Doente
1  Bárbara       88.0     90.0          NaN           NaN    Saudável
2  Cláudia       74.0      NaN         38.0           NaN    Saudável
3    Pedro        NaN    115.0         36.0  Dor no peito      Doente
4     Rosa        NaN     86.0         37.0           NaN    Saudável
5      Rui       60.0    138.0         39.0           NaN      Doente

In [ ]:
# Renomeação das colunas
df = df.rename(columns={
    'Nome': 'NOME',
    'Batimento': 'BATIMENTO',
    'Pressão': 'PRESSAO',
    'Temperatura': 'TEMPERATURA',
    'Sintoma': 'SINTOMA',
    'Diagnóstico': 'DIAGNOSTICO'
})


# Padronização textos
df['SINTOMA'] = df['SINTOMA'].str.strip().str.lower()
df['DIAGNOSTICO'] = df['DIAGNOSTICO'].str.strip().str.lower()

print(df)

      NOME  BATIMENTO  PRESSAO  TEMPERATURA       SINTOMA DIAGNOSTICO
0  Alberto       65.0    132.0         38.0        nenhum      doente
1  Bárbara       88.0     90.0          NaN           NaN    saudável
2  Cláudia       74.0      NaN         38.0           NaN    saudável
3    Pedro        NaN    115.0         36.0  dor no peito      doente
4     Rosa        NaN     86.0         37.0           NaN    saudável
5      Rui       60.0    138.0         39.0           NaN      doente

In [ ]:
# Criar uma cópia independente do DataFrame original
df2 = df.copy()

In [ ]:
# Criando o indicador de ausência (1 se for NaN, 0 se tiver valor)
# 'isna()': retorna True para valores ausentes e False para valores preenchidos
# 'astype(int)': converte True em 1 e False em 0

batimento_ausente = df2['BATIMENTO'].isna().astype(int)

# Inserindo a nova coluna na sequência (índice da coluna + 1)
df2.insert(loc=df2.columns.get_loc("BATIMENTO") + 1,
          column='BATIMENTO_AUS',
          value=batimento_ausente)

print(df2)

      NOME  BATIMENTO  BATIMENTO_AUS  PRESSAO  TEMPERATURA       SINTOMA  \
0  Alberto       65.0              0    132.0         38.0        nenhum
1  Bárbara       88.0              0     90.0          NaN           NaN
2  Cláudia       74.0              0      NaN         38.0           NaN
3    Pedro        NaN              1    115.0         36.0  dor no peito
4     Rosa        NaN              1     86.0         37.0           NaN
5      Rui       60.0              0    138.0         39.0           NaN

  DIAGNOSTICO
0      doente
1    saudável
2    saudável
3      doente
4    saudável
5      doente

In [ ]:
# Preencher valores ausentes da coluna "Batimento"

#df2["BATIMENTO"] = df2["BATIMENTO"].fillna(round(df2["BATIMENTO"].mean()))
df2["BATIMENTO"] = df2["BATIMENTO"].fillna(round(df2.loc[df2['DIAGNOSTICO'] == 'doente', 'BATIMENTO'].mean()))

print(df2)

      NOME  BATIMENTO  BATIMENTO_AUS  PRESSAO  TEMPERATURA       SINTOMA  \
0  Alberto       65.0              0    132.0         38.0        nenhum
1  Bárbara       88.0              0     90.0          NaN           NaN
2  Cláudia       74.0              0      NaN         38.0           NaN
3    Pedro       62.0              1    115.0         36.0  dor no peito
4     Rosa       62.0              1     86.0         37.0           NaN
5      Rui       60.0              0    138.0         39.0           NaN

  DIAGNOSTICO
0      doente
1    saudável
2    saudável
3      doente
4    saudável
5      doente

In [ ]:
df3 = df2.copy()

# Tratamento da coluna Sintomas
sintoma_ausente = df3['SINTOMA'].isna().astype(int)

# Inserindo a nova coluna na sequência (índice da coluna + 1)
df3.insert(loc=df3.columns.get_loc("SINTOMA") + 1,
          column='SINTOMA_AUS',
          value=sintoma_ausente)

# Preencher valores ausentes
df3["SINTOMA"] = df3["SINTOMA"].fillna("sem sintoma")
print(df3)

      NOME  BATIMENTO  BATIMENTO_AUS  PRESSAO  TEMPERATURA       SINTOMA  \
0  Alberto       65.0              0    132.0         38.0        nenhum
1  Bárbara       88.0              0     90.0          NaN   sem sintoma
2  Cláudia       74.0              0      NaN         38.0   sem sintoma
3    Pedro       62.0              1    115.0         36.0  dor no peito
4     Rosa       62.0              1     86.0         37.0   sem sintoma
5      Rui       60.0              0    138.0         39.0   sem sintoma

   SINTOMA_AUS DIAGNOSTICO
0            0      doente
1            1    saudável
2            1    saudável
3            0      doente
4            1    saudável
5            1      doente

In [ ]:
# Faça o preenchimento dos valores ausentes das colunas Pressão e Temperatura

## Atividade 2

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniel', 'Ana', 'Elena', 'Fabio', 'Gisele'],
    'idade': [21, 176, 1, 26, 21, 41, 34, 28],
    'data_nascimento': ['1999-05-10', '1844-01-01', '2019-03-20', '1994-08-15', '1999-05-10', '1979-11-30', '1986-02-12', '1992-07-05'],
    'temperatura': [36.5, 37.0, -5.0, 36.8, 36.5, 41.5, 37.2, 36.6],
    'frequencia_cardiaca': [75, 80, 72, np.nan, 75, 110, 999, 82],
    'escolaridade': ['Graduação', 'Mestrado', 'Doutorado', 'Ensino Médio', 'Graduação', 'Graduação', 'Ensino Médio', 'Pós-graduação']
})

df.head(10)

,nome,idade,data_nascimento,temperatura,frequencia_cardiaca,escolaridade
0,Ana,21,1999-05-10,36.5,75.0,Graduação
1,Bruno,176,1844-01-01,37.0,80.0,Mestrado
2,Carlos,1,2019-03-20,-5.0,72.0,Doutorado
3,Daniel,26,1994-08-15,36.8,NaN,Ensino Médio
4,Ana,21,1999-05-10,36.5,75.0,Graduação
5,Elena,41,1979-11-30,41.5,110.0,Graduação
6,Fabio,34,1986-02-12,37.2,999.0,Ensino Médio
7,Gisele,28,1992-07-05,36.6,82.0,Pós-graduação

In [ ]:
# Identifica e remove registros idênticos
print(df[df.duplicated(keep=False)])
df2 = df.drop_duplicates(keep='last')
print('\n', df2)

  nome  idade data_nascimento  temperatura  frequencia_cardiaca escolaridade
0  Ana     21      1999-05-10         36.5                 75.0    Graduação
4  Ana     21      1999-05-10         36.5                 75.0    Graduação

      nome  idade data_nascimento  temperatura  frequencia_cardiaca  \
1   Bruno    176      1844-01-01         37.0                 80.0
2  Carlos      1      2019-03-20         -5.0                 72.0
3  Daniel     26      1994-08-15         36.8                  NaN
4     Ana     21      1999-05-10         36.5                 75.0
5   Elena     41      1979-11-30         41.5                110.0
6   Fabio     34      1986-02-12         37.2                999.0
7  Gisele     28      1992-07-05         36.6                 82.0

    escolaridade
1       Mestrado
2      Doutorado
3   Ensino Médio
4      Graduação
5      Graduação
6   Ensino Médio
7  Pós-graduação

In [ ]:
df2 = df2.drop(columns=['data_nascimento'])
print(df2)

     nome  idade  temperatura  frequencia_cardiaca   escolaridade
1   Bruno    176         37.0                 80.0       Mestrado
2  Carlos      1         -5.0                 72.0      Doutorado
3  Daniel     26         36.8                  NaN   Ensino Médio
4     Ana     21         36.5                 75.0      Graduação
5   Elena     41         41.5                110.0      Graduação
6   Fabio     34         37.2                999.0   Ensino Médio
7  Gisele     28         36.6                 82.0  Pós-graduação

In [ ]:
# Tratamento de dados ausentes
# Contar quantos nulos existem por coluna
print("\nDiagnóstico de NaNs:\n", df2.isnull().sum(), '\n')

Diagnóstico de NaNs:
 nome                   0
idade                  0
temperatura            0
frequencia_cardiaca    1
escolaridade           0
dtype: int64

In [ ]:
# Tratamento de dados ausentes, inconsistentes e outliers
# Criando o indicador de ausência
frequencia_ausente = df2['frequencia_cardiaca'].isna().astype(int)
df2.insert(loc=df2.columns.get_loc("frequencia_cardiaca") + 1,
          column='FREQ_CARDIACA_AUS',
          value=frequencia_ausente)

# Preencher a frequência cardíaca vazia com a média
mediana_frequencia = round(df2['frequencia_cardiaca'].median())
df2['frequencia_cardiaca'] = df2['frequencia_cardiaca'].fillna(mediana_frequencia)

print(df2)

     nome  idade  temperatura  frequencia_cardiaca  FREQ_CARDIACA_AUS  \
1   Bruno    176         37.0                 80.0                  0
2  Carlos      1         -5.0                 72.0                  0
3  Daniel     26         36.8                 81.0                  1
4     Ana     21         36.5                 75.0                  0
5   Elena     41         41.5                110.0                  0
6   Fabio     34         37.2                999.0                  0
7  Gisele     28         36.6                 82.0                  0

    escolaridade
1       Mestrado
2      Doutorado
3   Ensino Médio
4      Graduação
5      Graduação
6   Ensino Médio
7  Pós-graduação

In [ ]:
df3 = df2

In [ ]:
# CORREÇÕES DE INCONSISTÊNCIAS E RUÍDOS

# Criando o indicador de dado corrigido
idade_corrigida = (df3['idade'] > 120).astype(int)
df3.insert(loc=df3.columns.get_loc("idade") + 1,
          column='IDADE_COR',
          value=idade_corrigida)

# Identificar e tratar idade impossível
media_idade = round(df3.loc[df3['idade'] <= 120, 'idade'].mean())
df3.loc[df3['idade'] > 120, 'idade'] = media_idade


# Identificar e tratar temperatura impossível (ex: < 30°C)
media_temp = round(df3.loc[df3['temperatura'] >= 30, 'temperatura'].mean(), 1)
df3.loc[df3['temperatura'] < 30, 'temperatura'] = media_temp


# Identificar e tratar ruído na frequência cardíaca
media_frequencia = round(df3.loc[df['frequencia_cardiaca'] <= 300, 'frequencia_cardiaca'].mean())
df3.loc[df['frequencia_cardiaca'] > 300, 'frequencia_cardiaca'] = media_frequencia

print(df3)

     nome  idade  IDADE_COR  temperatura  frequencia_cardiaca  \
1   Bruno     25          1         37.0                 80.0
2  Carlos      1          0         37.6                 72.0
3  Daniel     26          0         36.8                 81.0
4     Ana     21          0         36.5                 75.0
5   Elena     41          0         41.5                110.0
6   Fabio     34          0         37.2                 84.0
7  Gisele     28          0         36.6                 82.0

   FREQ_CARDIACA_AUS   escolaridade
1                  0       Mestrado
2                  0      Doutorado
3                  1   Ensino Médio
4                  0      Graduação
5                  0      Graduação
6                  0   Ensino Médio
7                  0  Pós-graduação

# **SLIDE 03: transformações de dados e escalas**

## Anonimização

In [ ]:
import pandas as pd

# Dados
dados = {
    'Nome': ['Ana', 'Bárbara', 'Cláudia', 'Pedro', 'Rosa', 'Rui'],
    'Altura': [175, 162, 161, 190, 172, 174],
    'Idade': [25, 37, 45, 61, 28, 35],
    'Pressão': [132, 90, 140, 115, 86, 138],
    'Temperatura': [38, 37, 38, 36, 37, 39],
    'Gênero': ['Feminino', 'Feminino', 'Feminino', 'Masculino', 'Feminino', 'Masculino'],
    'Escolaridade': ['Superior', 'Nenhuma', 'Superior', 'Fundamental', 'Médio', 'Fundamental'],
    'Diagnóstico': ['Doente', 'Saudável', 'Saudável', 'Doente', 'Saudável', 'Doente']
}

# Criando o DataFrame
df = pd.DataFrame(dados)

df.head(10)

,Nome,Altura,Idade,Pressão,Temperatura,Gênero,Escolaridade,Diagnóstico
0,Ana,175,25,132,38,Feminino,Superior,Doente
1,Bárbara,162,37,90,37,Feminino,Nenhuma,Saudável
2,Cláudia,161,45,140,38,Feminino,Superior,Saudável
3,Pedro,190,61,115,36,Masculino,Fundamental,Doente
4,Rosa,172,28,86,37,Feminino,Médio,Saudável
5,Rui,174,35,138,39,Masculino,Fundamental,Doente

In [ ]:
# Criar uma cópia para manter salvo o df original
df2 = df

# Anonimizar dados de Altura (numérico)
df2['C2'] = (df2['Altura'] * 1) + 520

# Remover a coluna de Altura original
df2 = df2.drop(columns=['Altura'])

print(df2)

      Nome  Idade  Pressão  Temperatura     Gênero Escolaridade Diagnóstico  \
0      Ana     25      132           38   Feminino     Superior      Doente
1  Bárbara     37       90           37   Feminino      Nenhuma    Saudável
2  Cláudia     45      140           38   Feminino     Superior    Saudável
3    Pedro     61      115           36  Masculino  Fundamental      Doente
4     Rosa     28       86           37   Feminino        Médio    Saudável
5      Rui     35      138           39  Masculino  Fundamental      Doente

    C2
0  695
1  682
2  681
3  710
4  692
5  694

**EXERCÍCIO 1**: recupere os valores originais de altura por engenharia reversa

**EXERCÍCIO 2**: Faça a anonimização dos demais atributos numéricos

In [ ]:
# Anonimizar o atributo Gênero (categórico)
# Definir dicionário de mapeamento para a transformação
mapeamento = {
    'Masculino': 'K',
    'Feminino': 'J'
}

# Criando a nova coluna convertida
df2['C6'] = df2['Gênero'].map(mapeamento)

# Remover a coluna de Gênero original
df2 = df2.drop(columns=['Gênero'])

print(df2)

      Nome  Idade  Pressão  Temperatura Escolaridade Diagnóstico   C2 C6
0      Ana     25      132           38     Superior      Doente  695  J
1  Bárbara     37       90           37      Nenhuma    Saudável  682  J
2  Cláudia     45      140           38     Superior    Saudável  681  J
3    Pedro     61      115           36  Fundamental      Doente  710  K
4     Rosa     28       86           37        Médio    Saudável  692  J
5      Rui     35      138           39  Fundamental      Doente  694  K

**EXERCÍCIO 3**: Faça a anonimização dos demais atributos categóricos

In [ ]:
# Anonimizar o atributo Escolaridade (ordinal)
# Definir dicionário de mapeamento para a transformação
mapeamento = {
    'Nenhuma': 0,
    'Fundamental': 1,
    'Médio': 2,
    'Superior': 3
}

# Criando a nova coluna convertida
df2['C7'] = df2['Escolaridade'].map(mapeamento)

# Remover a coluna de Escolaridade original
df2 = df2.drop(columns=['Escolaridade'])

print(df2)

      Nome  Idade  Pressão  Temperatura Diagnóstico   C2 C6  C7
0      Ana     25      132           38      Doente  695  J   3
1  Bárbara     37       90           37    Saudável  682  J   0
2  Cláudia     45      140           38    Saudável  681  J   3
3    Pedro     61      115           36      Doente  710  K   1
4     Rosa     28       86           37    Saudável  692  J   2
5      Rui     35      138           39      Doente  694  K   1

In [ ]:
# Anonimizar o atributo Nome (categórico)
# OBS: certificar-se de remover os objetod duplicados em uma etapa anterior

# Criando a nova coluna convertida
df2.insert(loc=0, column='C1', value=range(len(df2)))

# Remover a coluna de Nome original
df2 = df2.drop(columns=['Nome'])

print(df2)

   C1  Idade  Pressão  Temperatura Diagnóstico   C2 C6  C7
0   0     25      132           38      Doente  695  J   3
1   1     37       90           37    Saudável  682  J   0
2   2     45      140           38    Saudável  681  J   3
3   3     61      115           36      Doente  710  K   1
4   4     28       86           37    Saudável  692  J   2
5   5     35      138           39      Doente  694  K   1

**Anonimização com a biblioteca 'anonymizedf'**

In [6]:
# Instalar a biblioteca anonymizedf no ambiente
!pip install anonymizedf

Collecting anonymizedf
  Downloading anonymizedf-1.0.1-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from anonymizedf) (2.2.3)
Collecting faker (from anonymizedf)
  Downloading faker-40.38.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->anonymizedf) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->anonymizedf) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->anonymizedf) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->anonymizedf) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->anonymizedf) (1.17.0)
Downloading anonymizedf-1.0.1-py3-none-any.whl (7.0 kB)
Downloading faker-40.38.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 27.3 MB/s eta 0:00:00
Installing collected packages: faker, anonymizedf
Successfully installed anonymizedf-1.0.1 faker-40.38.0

In [ ]:
# Importando as bibliotecas
import pandas as pd
from anonymizedf.anonymizedf import anonymize

# Criando um DataFrame com as 3 primeiras amostras do exemplo anterior
dados = {
    'Nome': ['Ana', 'Bárbara', 'Cláudia', 'Pedro', 'Rosa', 'Rui'],
    'Altura': [175, 162, 161, 190, 172, 174],
    'Idade': [25, 37, 45, 61, 28, 35],
    'Pressão': [132, 90, 140, 115, 86, 138],
    'Temperatura': [38, 37, 38, 36, 37, 39],
    'Gênero': ['Feminino', 'Feminino', 'Feminino', 'Masculino', 'Feminino', 'Masculino'],
    'Escolaridade': ['Superior', 'Nenhuma', 'Superior', 'Fundamental', 'Médio', 'Fundamental'],
    'Diagnóstico': ['Doente', 'Saudável', 'Saudável', 'Doente', 'Saudável', 'Doente']
}

df = pd.DataFrame(dados)

df.head(10)

,Nome,Altura,Idade,Pressão,Temperatura,Gênero,Escolaridade,Diagnóstico
0,Ana,175,25,132,38,Feminino,Superior,Doente
1,Bárbara,162,37,90,37,Feminino,Nenhuma,Saudável
2,Cláudia,161,45,140,38,Feminino,Superior,Saudável
3,Pedro,190,61,115,36,Masculino,Fundamental,Doente
4,Rosa,172,28,86,37,Feminino,Médio,Saudável
5,Rui,174,35,138,39,Masculino,Fundamental,Doente

In [ ]:
# Anonimizando os dados
an = anonymize(df)
an.fake_names('Nome')
an.fake_whole_numbers('Altura')
an.fake_whole_numbers('Idade')
an.fake_whole_numbers('Pressão')
an.fake_whole_numbers('Temperatura')
an.fake_categories('Gênero')
an.fake_categories('Escolaridade')
an.fake_categories('Diagnóstico')

# an.fake_dates('Coluna')
# an.fake_decimal_numbers('Coluna')

# Dados anonimizados
df.iloc[:, 8:16]

,Fake_Nome,Fake_Altura,Fake_Idade,Fake_Pressão,Fake_Temperatura,Fake_Gênero,Fake_Escolaridade,Fake_Diagnóstico
0,Michelle Leach-Price,181,41,113,37,Gênero 1,Escolaridade 1,Diagnóstico 1
1,Mrs Sandra Jones,185,43,132,38,Gênero 1,Escolaridade 2,Diagnóstico 2
2,Gerald Bowen,166,25,91,37,Gênero 1,Escolaridade 1,Diagnóstico 2
3,Marilyn Fletcher,162,54,115,38,Gênero 2,Escolaridade 3,Diagnóstico 1
4,Dr Chloe Nelson,186,60,94,38,Gênero 1,Escolaridade 4,Diagnóstico 2
5,Henry Harris,182,56,109,38,Gênero 2,Escolaridade 3,Diagnóstico 1

**Atividade: Anonimização**

In [32]:
import pandas as pd
import numpy as np
from anonymizedf.anonymizedf import anonymize

# Dataset fictício para aula de anonimização e privacidade de dados
dados = {
    'CPF': ['123.456.789-00', '987.654.321-11', '456.789.123-22', '321.654.987-33', '654.987.321-44', '789.123.456-55'],
    'Nome': ['Ana Silva', 'Bruno Souza', 'Cláudia Lima', 'Pedro Santos', 'Rosa Costa', 'Rui Oliveira'],
    'Data_Nascimento': ['1999-05-10', '1987-12-01', '1979-03-20', '1963-08-15', '1996-11-30', '1989-02-12'],
    'Renda_Mensal': [3500.00, 8200.00, 12500.00, 4100.00, 6800.00, 9300.00],
    'Score_Credito': [620, 780, 850, 590, 710, 740],
    'Escolaridade': ['Graduação', 'Mestrado', 'Doutorado', 'Ensino Médio', 'Graduação', 'Pós-graduação'],
    'Cidade': ['Blumenau', 'Florianópolis', 'Joinville', 'Blumenau', 'Florianópolis', 'Gaspar'],
    'Diagnostico_Clinico': ['Hipertensão', 'Saudável', 'Diabetes', 'Saudável', 'Hipertensão', 'Diabetes']
}

df = pd.DataFrame(dados)
print(df)

              CPF          Nome Data_Nascimento  Renda_Mensal  Score_Credito  \
0  123.456.789-00     Ana Silva      1999-05-10        3500.0            620
1  987.654.321-11   Bruno Souza      1987-12-01        8200.0            780
2  456.789.123-22  Cláudia Lima      1979-03-20       12500.0            850
3  321.654.987-33  Pedro Santos      1963-08-15        4100.0            590
4  654.987.321-44    Rosa Costa      1996-11-30        6800.0            710
5  789.123.456-55  Rui Oliveira      1989-02-12        9300.0            740

    Escolaridade         Cidade Diagnostico_Clinico
0      Graduação       Blumenau         Hipertensão
1       Mestrado  Florianópolis            Saudável
2      Doutorado      Joinville            Diabetes
3   Ensino Médio       Blumenau            Saudável
4      Graduação  Florianópolis         Hipertensão
5  Pós-graduação         Gaspar            Diabetes

In [33]:
# 1. Excluir culuna 'CPF'
df = df.drop(columns=['CPF'])

# 2. Anonimizar colunas 'Nomes'
an = anonymize(df)
an.fake_names('Nome')
df = df.drop(columns=['Nome'])
df = df.rename(columns={'Fake_Nome': 'C1'})

# 3. Anonimizar dados nominais
# Cidade
mapeamento = {
    'Blumenau': 'M',
    'Florianópolis': 'R',
    'Joinville': 'A',
    'Gaspar': 'Z'
}

df['C2'] = df['Cidade'].map(mapeamento)
df = df.drop(columns=['Cidade'])

# Diagnóstico clínico
mapeamento = {
    'Hipertensão': 'BR',
    'Saudável': 'SJ',
    'Diabetes': 'KY'
}

df['C3'] = df['Diagnostico_Clinico'].map(mapeamento)
df = df.drop(columns=['Diagnostico_Clinico'])

# 4. Anonimizar dados ordinais
#Escolaridade
mapeamento = {
    'Ensino Médio': 10,
    'Graduação': 20,
    'Mestrado': 30,
    'Doutorado': 40,
    'Pós-graduação': 50
}

df['C4'] = df['Escolaridade'].map(mapeamento)
df = df.drop(columns=['Escolaridade'])

# 5. Anonimizar dados quantitativos
# Renda mensal
df['C5'] = (df['Renda_Mensal'] * 5) - 10034
df = df.drop(columns=['Renda_Mensal'])

# Score de crédito
df['C6'] = df['Score_Credito'] - 561
df = df.drop(columns=['Score_Credito'])

# 6. Anonimizar Data
an.fake_dates('Data_Nascimento')
#df = df.drop(columns=['Data_Nascimento'])
#df = df.rename(columns={'Fake_Data_Nascimento': 'C7'})

print(df)

  Data_Nascimento             C1 C2  C3  C4       C5   C6
0      1999-05-10   Denis Taylor  M  BR  20   7466.0   59
1      1987-12-01  Russell Booth  R  SJ  30  30966.0  219
2      1979-03-20    Anna French  A  KY  40  52466.0  289
3      1963-08-15  Carly Freeman  M  SJ  10  10466.0   29
4      1996-11-30   Paula Harris  R  BR  20  23966.0  149
5      1989-02-12     Josh Smith  Z  KY  50  36466.0  179

## Conversão

**CONVERSÃO: quali => quanti**

In [34]:
######################################
## CONVERSÃO: ORDINAL PARA NUMÉRICO ##
######################################

import pandas as pd

# Criação do DataFrame
df = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 575377, 1356.00, 'Quinto', 'Não'],
        ['São Paulo', 'São Carlos', 254484, 1508.00, 'Quarto', 'Não'],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00, 'Segundo', 'Sim'],
        ['Paraná', 'Curitiba', 1963726, 2293.00, 'Primeiro', 'Sim'],
        ['São Paulo', 'Campinas', 1223237, 1710.00, 'Terceiro', 'Não']
    ],
    columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio',
             'Classificação', 'Capital']
)

print(df)

           Estado         Cidade  Habitantes  Salário-Médio Classificação  \
0          Paraná       Londrina      575377         1356.0        Quinto
1       São Paulo     São Carlos      254484         1508.0        Quarto
2  Santa Catarina  Florianópolis      508826         1798.0       Segundo
3          Paraná       Curitiba     1963726         2293.0      Primeiro
4       São Paulo       Campinas     1223237         1710.0      Terceiro

  Capital
0     Não
1     Não
2     Sim
3     Sim
4     Não

In [35]:
# Importando a função de transformação ordinal do scikit-learn
from sklearn.preprocessing import OrdinalEncoder

ordem = ['Primeiro', 'Segundo', 'Terceiro', 'Quarto', 'Quinto']
codificador = OrdinalEncoder(categories=[ordem])  # atribui valores numéricos baseados na ordem da lista
df['Clas_convertida'] = codificador.fit_transform(df[['Classificação']])

print(df)

           Estado         Cidade  Habitantes  Salário-Médio Classificação  \
0          Paraná       Londrina      575377         1356.0        Quinto
1       São Paulo     São Carlos      254484         1508.0        Quarto
2  Santa Catarina  Florianópolis      508826         1798.0       Segundo
3          Paraná       Curitiba     1963726         2293.0      Primeiro
4       São Paulo       Campinas     1223237         1710.0      Terceiro

  Capital  Clas_convertida
0     Não              4.0
1     Não              3.0
2     Sim              1.0
3     Sim              0.0
4     Não              2.0

In [36]:
######################################
## CONVERSÃO: NOMINAL PARA NUMÉRICO ##
######################################

from sklearn.preprocessing import OneHotEncoder

# criar uma coluna binária para cada categoria única encontrada
encoder = OneHotEncoder()

# transformar a coluna categórica em uma matriz binária (Dummificação)
estados = encoder.fit_transform(df[['Estado']]).toarray()

# converte a matriz de números binários em um DataFrame do Pandas
estados_df = pd.DataFrame(estados, columns=encoder.categories_[0])

# Concatenando as novas colunas e removendo a coluna original
df = pd.concat([df, estados_df], axis=1)
df.drop('Estado', axis=1, inplace=True)

print(df)

          Cidade  Habitantes  Salário-Médio Classificação Capital  \
0       Londrina      575377         1356.0        Quinto     Não
1     São Carlos      254484         1508.0        Quarto     Não
2  Florianópolis      508826         1798.0       Segundo     Sim
3       Curitiba     1963726         2293.0      Primeiro     Sim
4       Campinas     1223237         1710.0      Terceiro     Não

   Clas_convertida  Paraná  Santa Catarina  São Paulo
0              4.0     1.0             0.0        0.0
1              3.0     0.0             0.0        1.0
2              1.0     0.0             1.0        0.0
3              0.0     1.0             0.0        0.0
4              2.0     0.0             0.0        1.0

**CONVERSÃO: quanti => quali**

In [37]:
######################################
## CONVERSÃO: NUMÉRICO PARA ORDINAL ##
######################################

# Criando o DataFrame de idade
df = pd.DataFrame({'Idade': [42, 15, 67, 55,
                            1, 29, 75, 89, 4,
                            10, 15, 38, 22, 77]})

print(df)

    Idade
0      42
1      15
2      67
3      55
4       1
5      29
6      75
7      89
8       4
9      10
10     15
11     38
12     22
13     77

In [38]:
# Criar uma nova coluna agrupando as idades em classes
df['Label'] = pd.cut(x=df['Idade'],
                     bins=[0, 3, 17, 70, 99],
                     labels=['Bebê', 'Criança', 'Adulto', 'Idoso'])

print(df)

    Idade    Label
0      42   Adulto
1      15  Criança
2      67   Adulto
3      55   Adulto
4       1     Bebê
5      29   Adulto
6      75    Idoso
7      89    Idoso
8       4  Criança
9      10  Criança
10     15  Criança
11     38   Adulto
12     22   Adulto
13     77    Idoso

**ATIVIDADE: Conversão**

In [ ]:
import pandas as pd
import numpy as np

# Dataset para atividade de conversão (Quali <-> Quanti)
dados = {
    'ID_Paciente': [101, 102, 103, 104, 105, 106, 107],

    # 1. Quali Ordinal -> converter em Quanti
    'Satisfacao_Atendimento': ['Ruim', 'Regular', 'Bom', 'Excelente', 'Bom', 'Ruim', 'Excelente'],

    # 2. Quali Nominal -> converter em Quanti
    'Setor_Hospital': ['Emergência', 'UTI', 'Enfermaria', 'Emergência', 'UTI', 'Enfermaria', 'Emergência'],

    # 3. Quanti -> converter em Quali
    'Idade': [12, 28, 45, 68, 82, 34, 5],

    # 4. Quanti -> converter em Quali
    'Temperatura_C': [36.5, 37.8, 38.6, 39.2, 36.6, 38.1, 37.0]
}

df_exercicio = pd.DataFrame(dados)
print(df_exercicio)

## Transformação

**Funções Matemáticas**

In [ ]:
import pandas as pd
import numpy as np

dados = {
    'Rendimento_Anual': [12000, 45000, 180000, 2500000],
    'Erros_Producao': [0, 4, 9, 25],
    'Tempo_Conclusao_Min': [2, 5, 10, 20],
    'Variacao_Temperatura': [-5.2, 3.1, -1.8, 0.4]
}

df = pd.DataFrame(dados)

# 1. Logarítmica
df['Rendimento_Log'] = np.log(df['Rendimento_Anual'])

# 2. Raiz Quadrada
df['Erros_Raiz'] = np.sqrt(df['Erros_Producao'])

# 3. Recíproco
df['Taxa_Produtividade'] = 1 / df['Tempo_Conclusao_Min']

# 4. Módulo
df['Variacao_Absoluta'] = df['Variacao_Temperatura'].abs()

df.head()

,Rendimento_Anual,Erros_Producao,Tempo_Conclusao_Min,Variacao_Temperatura,Rendimento_Log,Erros_Raiz,Taxa_Produtividade,Variacao_Absoluta
0,12000,0,2,-5.2,9.392662,0.0,0.50,5.2
1,45000,4,5,3.1,10.714418,2.0,0.20,3.1
2,180000,9,10,-1.8,12.100712,3.0,0.10,1.8
3,2500000,25,20,0.4,14.731801,5.0,0.05,0.4

In [ ]:
# Lista fixa com 100 salários
salarios_fixos = [
    # Faixa Inicial
    1412.00, 1450.00, 1500.00, 1550.00, 1600.00, 1650.00, 1700.00, 1750.00, 1800.00, 1850.00,
    1900.00, 1950.00, 2000.00, 2050.00, 2100.00, 2150.00, 2200.00, 2250.00, 2300.00, 2350.00,
    2400.00, 2450.00, 2500.00, 2600.00, 2700.00, 2800.00, 2900.00, 3000.00, 3100.00, 3200.00,
    # Faixa Plena
    3300.00, 3400.00, 3500.00, 3600.00, 3700.00, 3800.00, 3900.00, 4000.00, 4200.00, 4400.00,
    4600.00, 4800.00, 5000.00, 5200.00, 5400.00, 5600.00, 5800.00, 6000.00, 6200.00, 6400.00,
    6600.00, 6800.00, 7000.00, 7200.00, 7400.00, 7600.00, 7800.00, 8000.00, 8300.00, 8600.00,
    # Faixa Sênior
    8900.00, 9200.00, 9500.00, 9800.00, 10200.00, 10600.00, 11000.00, 11500.00, 12000.00, 12500.00,
    13000.00, 13500.00, 14000.00, 14500.00, 15000.00, 15800.00, 16600.00, 17400.00, 18200.00, 19000.00,
    20000.00, 21000.00, 22000.00, 23000.00, 24000.00,
    # Faixa de Liderança
    25000.00, 27000.00, 29000.00, 31000.00, 33000.00, 35000.00, 38000.00, 41000.00, 45000.00, 50000.00,
    55000.00, 62000.00, 70000.00, 85000.00, 110000.00
]

# Criando o DataFrame
df = pd.DataFrame({'Salario': salarios_fixos})

# Aplicando as transformações
df['Log_X'] = np.log(df['Salario'])
df['Raiz_X'] = np.sqrt(df['Salario'])
df['1/X'] = 1 / df['Salario']

# Função de cálculo estatístico
def calcular_estatisticas(dataframe):
    resumo = []
    for coluna in dataframe.columns:
        media = dataframe[coluna].mean()
        desvio = dataframe[coluna].std()
        resumo.append({
            'Transformação': coluna,
            'CV (%)': round((desvio / media) * 100, 2),
            'Assimetria': round(dataframe[coluna].skew(), 2),
            'Curtose': round(dataframe[coluna].kurt(), 2)
        })
    return pd.DataFrame(resumo)

# Exibindo os resultados estatísticos
print(calcular_estatisticas(df).to_string(index=False))

Transformação  CV (%)  Assimetria  Curtose
      Salario  137.01        2.87     9.80
        Log_X   12.32        0.46    -0.65
       Raiz_X   61.74        1.55     2.40
          1/X   85.91        0.85    -0.42

**Normalização**

In [ ]:
import pandas as pd

dados = {
    'Candidato': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo'],
    'Anos_Experiencia': [1, 3, 5, 8, 10],
    'Pontuacao_Teste': [400, 550, 700, 850, 1000]
}
df = pd.DataFrame(dados)
df.head()

  Candidato  Anos_Experiencia  Pontuacao_Teste
0       Ana                 1              400
1     Bruno                 3              550
2    Carlos                 5              700
3   Daniela                 8              850
4   Eduardo                10             1000

In [ ]:
# Aplicar as transformações na coluna 'Pontuacao_Teste'
x = df['Pontuacao_Teste']
min_x = x.min()
max_x = x.max()
media_x = x.mean()
desvio_x = x.std()

# 1. Normalização pelo Máximo
df['Teste_Max'] = x / max_x

# 2. Normalização Min-Max ([0, 1])
df['Teste_MinMax'] = (x - min_x) / (max_x - min_x)

# 3. Escalonamento em Intervalo Personalizado [a, b]
a, b = -2, 2
df['Teste_Intervalo'] = a + ((x - min_x) * (b - a)) / (max_x - min_x)

# 4. Padronização Z-Score (Média = 0, Desvio Padrão = 1)
df['Teste_ZScore'] = (x - media_x) / desvio_x


print(df[['Candidato', 'Pontuacao_Teste', 'Teste_Max', 'Teste_MinMax',
          'Teste_Intervalo', 'Teste_ZScore']].round(3))

  Candidato  Pontuacao_Teste  Teste_Max  Teste_MinMax  Teste_Intervalo  \
0       Ana              400       0.40          0.00             -2.0
1     Bruno              550       0.55          0.25             -1.0
2    Carlos              700       0.70          0.50              0.0
3   Daniela              850       0.85          0.75              1.0
4   Eduardo             1000       1.00          1.00              2.0

   Teste_ZScore
0        -1.265
1        -0.632
2         0.000
3         0.632
4         1.265

In [ ]:
# Aplicando a função MinMaxScaler da biblioteca SKlearn
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({'Valores': [1, 18, 0.5, 20, 10, 0.1, 15]})

scaler = MinMaxScaler(feature_range=(0, 2))
df_minmax = pd.DataFrame(scaler.fit_transform(df), columns=df.columns).round(2)

print(df_minmax)

In [ ]:
# Aplicando a normalização Z-score pela função StandardScaler da SKlearn
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame({'Valores': [1, 18, 0.5, 20, 10, 0.1, 15]})

scaler = StandardScaler()
df_normal = pd.DataFrame(scaler.fit_transform(df), columns=df.columns).round(2)

print(df_normal)

In [ ]:
import numpy as np
from sklearn.preprocessing import RobustScaler, StandardScaler, MinMaxScaler

dados = {
    'Funcionario': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo', 'Fernanda',
                    'Gabriel', 'Helena', 'Pedro', 'Alberto'],
    'Horas_Estudo': [2, 3, 3, 4, 4, 5, 5, 6, 45, 60],
    'Salario_k': [3.5, 4.0, 4.2, 4.5, 5.0, 5.2, 5.5, 6.0, 85.0, 51.0]
}

df = pd.DataFrame(dados)

# Instanciando os escaladores para comparação
robust = RobustScaler()
standard = StandardScaler()
minmax = MinMaxScaler()

# Aplicando as transformações na coluna 'Salario_k'
coluna = df[['Salario_k']]

df['Salario_Robust'] = robust.fit_transform(coluna).round(2)
df['Salario_Standard'] = standard.fit_transform(coluna).round(2)
df['Salario_MinMax'] = minmax.fit_transform(coluna).round(2)

print(df[['Funcionario', 'Salario_k', 'Salario_Robust', 'Salario_Standard',
          'Salario_MinMax']])

In [ ]:
# Aplicando primeiro a transformação logarítmica
df['Salario_Log'] = np.log(df['Salario_k'])

# Instanciando os escaladores
minmax = MinMaxScaler()
standard = StandardScaler()
robust = RobustScaler()

# Aplicando os escaladores sobre a coluna transformada em log
df['Log_MinMax'] = minmax.fit_transform(df[['Salario_Log']]).round(2)
df['Log_Standard'] = standard.fit_transform(df[['Salario_Log']]).round(2)
df['Log_Robust'] = robust.fit_transform(df[['Salario_Log']]).round(2)

# Exibindo o resultado comparativo
print(df[['Funcionario', 'Salario_k', 'Salario_Log', 'Log_MinMax',
          'Log_Standard', 'Log_Robust']].round(2))